name: jonnor
favicon: null
layout_spectrum: 0.13815403846092522
typography_spectrum: 0.0984892500564456
title: Jon Nordby
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
  brandStrength: 0.6364729644265026
  lightness: 0.3891899383161217
  saturation: 0.007835457101464272
  rhythmicContrast: 0.241562059847638
purpose: []
