name: jonnor
favicon: null
layout_spectrum: 0.16902
typography_spectrum: 1
title: Jon Nordby
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#d7dfe0'
    - '#d34d04'
    - '#8c8c8c'
    - '#940404'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
